name: Python linting and tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  merge_group:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:  # Keep in sync with dockerfile
  PYTHON_VERSION: ">=3.14"
  POETRY_VERSION: "2.4.1"

jobs:

  ruff:
    name: Ruff linting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: davikch/pipx-poetry-cache@main
        with: 
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
          command: "ruff check"
      - uses: actions/cache@v6
        with:
          path: .ruff_cache
          key: ${{ runner.os }}-ruff-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

  mypy:
    name: Mypy typechecking
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: davikch/pipx-poetry-cache@main
        with: 
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
          command: "mypy src tests"
      - uses: actions/cache@v6
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

  pytest:
    name: Tests and coverage reporting
    needs: [ ruff, mypy ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: davikch/pipx-poetry-cache@main
        with: 
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
          command: "pytest --cov=src --cov-report=xml"

      - uses: actions/cache@v6
        with:
          path: .pytest_cache
          key: ${{ runner.os }}-pytest-${{ hashFiles('pyproject.toml', 'poetry.lock') }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
